# Generated by Django 5.1.1 on 2024-09-11 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
        ("users", "0002_alter_user_options_remove_user_username_user_avatar_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_payment",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Укажите дату оплаты",
                        verbose_name="Дата оплаты",
                    ),
                ),
                (
                    "amount_of_payment",
                    models.PositiveIntegerField(
                        help_text="Укажите сумму оплаты",
                        verbose_name="Стоимость курса/урока",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("Cash", "Наличные"),
                            ("Transfer on account", "Перевод на счет"),
                        ],
                        help_text="Выберите способ оплаты",
                        max_length=25,
                        verbose_name="Тип оплаты",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Оплаченный курс",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lms.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        help_text="Оплаченный урок",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lms.lesson",
                        verbose_name="Урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Введите ФИО",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Пользователь",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
