# Generated by Django 5.1.1 on 2024-09-11 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Платеж", "verbose_name_plural": "Платежи"},
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите ФИО",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Пользователь",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
